#:kivy 1.0.9

<AsteroidsGame>:
    canvas:
        #Rectangle:
          #  pos: self.center_x-5, 0
          #  size: 10, self.height
    Button:
        font_size: 14
        center_x: root.width / 2
        top: root.top - 150
        text: root.hello_world
        on_press: root.button_pressed()


    Label:
        font_size: 40
        center_x: root.width / 2
        top: root.top - 5
        text: root.hello_world

